name: zeroe
channels:
  - defaults
  - fastai
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - tensorflow==2.0.0
  - nltk
  - scikit-learn
  - pandas
  - fastprogress
  - gensim
  - pillow
  - protobuf==3.8
  - tqdm
  - pytorch
  - torchvision
  - absl-py
  - pip:
    - seqeval==0.0.12
    - transformers==2.5.1

